name = "MinervaXAFS"
uuid = "0c4a189c-6bb9-4b91-a74d-78e8944992a9"
authors = ["itsgt <islagle3@gatech.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
